language: php
sudo: false

php: 7.1


cache:
  directories:
  - $HOME/.composer/cache

env:
  global:
  - SERVER_IP_ADDRESS=178.62.34.95
  - DEPLOY_DIR=/home/git/es-get-removed-subscribers

install: composer install

jobs:
  include:
  # Always build and test
  - stage: build
    script: $TRAVIS_BUILD_DIR/vendor/bin/phpunit

  # On master: deploy to DigitalOcean
  - stage: push
    if: branch = master AND type = push
    before_script:
    - openssl aes-256-cbc -K $encrypted_dc9d850b4010_key -iv $encrypted_dc9d850b4010_iv
      -in deploy_key.enc -out ./deploy_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./deploy_key
    - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./deploy_key
    - ssh -i ./deploy_key git@$SERVER_IP_ADDRESS pwd
    script: ./release.sh