version: '2'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                TIMEZONE: Europe/Paris
        volumes:
            - ./:/home/expertsender/get-removed-subscribers